### ISSUE TITLE
Comparison to SAM 

### ISSUE THREAD

**Issue by ClashLuke** [alessiosavi/OgameStats-init-cluster#1]
What's the difference between this and SAM? Do you aim to incorporate it in the future?

**Comment by alessiosavi** [comment]
Hi, `cdk` give you the possibility to define resources directly from your SDK. As you can create object (like `new Arraylist` or `new HashMap`), you can create AWS resources, like lambda, database or (quite) everything that you can create using the CloudFormation yaml configuration file.

There are several programming language supported.

It's very useful cause all the policy/role are added automagically.

An example, in order to give to a lambda the possibility to read and write into a DynamoDB table, you have only to write the following line:
https://github.com/alessiosavi/OgameStats-init-cluster/blob/bf36e79c3a213bbd93327372b2e47282660167d3/src/main/java/it/alessiosavi/cdk/initcluster/CdkInitClusterStack.java#L34

Where `playerData` is the DynamoDB table and `lambdaUpdater` is the lambda delegated to read/write from/into the DynamoDB table.

All resources that you define trough the `cdk` SDK, will be traduced into a CloudFormation stack.

Using `cdk synth`, you can view the `.yaml` template that will be deployed.

Using `cdk deploy` you will deploy the given stack.

All the resources (like lambda binary function) will be deployed to an S3 that is created during the `cdk bootstrap`, this command have to run only the first time that you want to use the CDK.

Another very important features, is that when you need to add some resources, you have only to modify the code without take care of manually modify the infrastructure. Instead, after you have created (or **modified**) a resources, you can view the difference from your new stack against the deployed stack using `cdk diff`. Now, you can re-run `cdk deploy` and modify your stack.

Using SAM or creating manually a CloudFormation stack (using yaml configuration file) can be a pain (a really pain, just think about the role of the resources when the project start to be quite big). Instead, with CDK you can only focus on the infrastructure design.

Note: every time that you have modified the code, you need to build the project using `mvn package`. You can modify the `cdk.json` as the following one in order to run the `mvn package` (or other necessary projects build) **every** time that you use the `cdk COMMAND`.

**Comment by ClashLuke** [comment]
I see, so the advantage of the cdk over a static sam template is that it's adaptive and can be changed using code, instead of having to copy a billion templates? That's amazing!

**Comment by alessiosavi** [comment]
Of course, you get the point.
This is a very basic course about the topic. Unfortunately it's far away for a complete courses, it's only a start point.
https://cdkworkshop.com/50-java/20-create-project.html
